theme: jekyll-theme-minimal
google_analytics: UA-151402-13
google_ad_client: ca-pub-7936772768451914

collections: 
  locations:
    output: true
    permalink: /:title

defaults:
  - scope:
      path: ""
      type: "locations"
    values:
      layout: "location"